const $=id=>document.getElementById(id),form=$('query'),canvas=$('chart'),ctx=canvas.getContext('2d');let currentBars=[],socket;
const now=new Date(),past=new Date(now-24*3600e3);$('from').value=past.toISOString().slice(0,16);$('to').value=now.toISOString().slice(0,16);
async function getJSON(path,options){const res=await fetch(path,options),data=await res.json();if(!res.ok)throw new Error(data.error||res.statusText);return data}
async function refreshAccount(){try{const [me,usage,providers,watchlist]=await Promise.all([getJSON('/v1/me'),getJSON('/v1/me/usage'),getJSON('/v1/providers/status'),getJSON('/v1/me/watchlist')]);$('account-name').textContent=`${me.name} · ${me.role}`;$('account-key').textContent=`Key ${me.key_name}${me.expires_at?` · ${new Date(me.expires_at).toLocaleDateString()} 到期`:''}`;$('account-requests').textContent=`${usage.current_minute.requests} / ${usage.quotas.requests_per_minute}`;$('account-daily').textContent=`今日 ${usage.daily.requests??0} 次`;$('account-datasets').textContent=`${usage.current_minute.datasets} / ${usage.quotas.datasets_per_minute}`;$('account-builds').textContent=`构建中 ${usage.active_builds} / ${usage.quotas.concurrent_builds}`;$('account-live').textContent=`连接 ${usage.live.connections} / ${usage.quotas.live_connections}`;$('account-symbols').textContent=`标的 ${usage.live.symbols} / ${usage.quotas.live_symbols}`;const massive=providers.massive||{};$('massive-status').textContent=massive.state||'unknown';$('massive-plan').textContent=massive.plan||'—';const lb=providers.longbridge||{};$('longbridge-status').textContent=lb.state||'unknown';$('longbridge-detail').textContent=`订阅池 ${lb.subscribed_symbols??0} · 重连 ${lb.reconnects??0}`;$('watchlist-symbols').value=(watchlist.symbols||[]).join(',');$('watchlist-state').textContent=`允许 ${(watchlist.allowed_symbols||[]).join(',')}`;$('status').textContent='账号在线';$('status').className='ok'}catch(err){$('status').textContent='账号状态不可用';$('status').className='bad'}}
refreshAccount();setInterval(refreshAccount,10000);
$('save-watchlist').addEventListener('click',async()=>{try{const symbols=$('watchlist-symbols').value.split(',').map(x=>x.trim()).filter(Boolean);await getJSON('/v1/me/watchlist',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols})});$('watchlist-state').textContent='已保存';await refreshAccount()}catch(err){$('watchlist-state').textContent=err.message}});
form.addEventListener('submit',async e=>{e.preventDefault();$('error').textContent='';try{const q=new URLSearchParams({interval:$('interval').value,from:new Date($('from').value).toISOString(),to:new Date($('to').value).toISOString(),session:'regular',adjustment:'split_adjusted'});const res=await fetch(`/v1/bars/${$('symbol').value.trim()}?${q}`),data=await res.json();if(!res.ok)throw new Error(data.error||res.statusText);$('source').textContent=`缓存：${data.source}`;$('count').textContent=`Bars：${data.bars.length}`;$('updated').textContent=`更新：${new Date().toLocaleTimeString()}`;currentBars=data.bars;draw(currentBars);connectLive()}catch(err){$('error').textContent=err.message}});
function connectLive(){if(socket)socket.close();const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}/v1/live/ws`);socket.onmessage=e=>{const event=JSON.parse(e.data);if(event.type!=='bar'||!event.bar)return;const index=currentBars.findIndex(b=>b.symbol===event.bar.symbol&&b.timestamp===event.bar.timestamp);if(index>=0)currentBars[index]=event.bar;else currentBars.push(event.bar);currentBars.sort((a,b)=>a.timestamp.localeCompare(b.timestamp)||a.symbol.localeCompare(b.symbol));draw(currentBars);$('updated').textContent=`更新：${new Date().toLocaleTimeString()}`};socket.onerror=()=>{$('status').textContent='实时连接异常'};socket.onopen=()=>{socket.send(JSON.stringify({action:'subscribe',symbols:[$('symbol').value.trim()],events:['bar']}));$('status').textContent='实时已连接'}}
function draw(bars){ctx.clearRect(0,0,canvas.width,canvas.height);if(!bars.length)return;const values=bars.flatMap(b=>[+b.high,+b.low]),lo=Math.min(...values),hi=Math.max(...values),pad=40,w=(canvas.width-pad*2)/bars.length,y=v=>pad+(hi-v)/(hi-lo||1)*(canvas.height-pad*2);ctx.strokeStyle='#1d3b32';for(let i=0;i<6;i++){const yy=pad+i*(canvas.height-pad*2)/5;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(canvas.width-pad,yy);ctx.stroke()}bars.forEach((b,i)=>{const x=pad+(i+.5)*w,up=+b.close>=+b.open;color=up?'#58d6a5':'#f06f78';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y(+b.high));ctx.lineTo(x,y(+b.low));ctx.stroke();const top=Math.min(y(+b.open),y(+b.close)),height=Math.max(1,Math.abs(y(+b.open)-y(+b.close)));ctx.fillRect(x-Math.max(1,w*.28),top,Math.max(2,w*.56),height)})}
form.requestSubmit();
